### ISSUE TITLE
transpile is no more needed, should be removed from documentation

### ISSUE THREAD

**Issue by IlyaSemenov** [wobsoriano/trpc-nuxt#240]
The documentation tells that one needs to transpile `trpc-nuxt`:

https://github.com/wobsoriano/trpc-nuxt/blob/3ac019ad74ca4378278b516dd6e641eeb8515d78/apps/docs/src/content/docs/setup.mdx#L43-L52

I believe in the latest version this is not needed. `dist/**/*.js` don't do any build-time imports like they apparently did before (#133).

Transpiling the package has negative side effects, for example it breaks `error instanceof TRPCClientError` since `TRPCClientError` coming from `@trpc/client` and `TRPCClientError` coming from the **transpiled** `trpc-nuxt` are different classes.

**Comment by kouts** [comment]
I think we might need to reconsider removing this from the documentation, as removing `trpc-nuxt` from `build.transpile` actually breaks the production server build (`nuxt build` followed by `nuxt preview` or `node .output/server/index.mjs`).

When `trpc-nuxt` is not transpiled, Nuxt automatically externalizes it in the server build. The problem is that `trpc-nuxt/dist/client/index.js` imports `nuxt/app`:

```javascript
import { useAsyncData, useRequestHeaders } from "nuxt/app";
```

Because the module is externalized, Node.js attempts to resolve `nuxt/app` at runtime. It resolves it to `node_modules/nuxt/dist/app/index.js`, which contains the following import:

```javascript
import "../../dist/app/types/augments";
```

Since `augments` is a TypeScript declaration file (`augments.d.ts`) and not a JavaScript file, Node.js throws an `ERR_MODULE_NOT_FOUND` error and the server crashes immediately on startup:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../.output/server/node_modules/nuxt/dist/app/types/augments' imported from '.../.output/server/node_modules/nuxt/dist/app/index.js'
```

Adding `trpc-nuxt` back to `build.transpile` fixes this because it allows Nuxt's bundler to correctly resolve the `nuxt/app` alias at build time rather than leaving it for Node.js to resolve at runtime. 

While I understand the `instanceof TRPCClientError` issue mentioned above, removing the transpile requirement completely breaks the production server for anyone using the client. Perhaps there's a different way to solve the `TRPCClientError` issue without breaking the server build?

cc @wobsoriano @IlyaSemenov

**Comment by IlyaSemenov** [comment]
@kouts I am using `nuxt-trpc` extensively in several projects (with production build of course) and all without transpile; however, I tried to come up with a minimal reproduction (to prove you wrong lol) and I actually repeated the problem. I suspect something has silently updated in Nuxt stack, will bisect and report.

Here's the minimal repro with latest versions:
https://stackblitz.com/edit/nuxt-starter-27yrcyhq

- `pnpm dev` → works
- `pnpm build && pnpm preview` → surfaces the problem

**Comment by IlyaSemenov** [comment]
@kouts I bisected this to SSR. In the repro above, try setting `{ ssr: false }` in `nuxt.config.ts` and the problem will go.

I believe this is an upstream bug, and we shouldn't "blindly" restore the documentation: either keep an open issue with "upstream" label, or restore the docs but explicitly state that this is a temporary workaround due to the current upstream problem.

**Comment by kouts** [comment]
@IlyaSemenov I'm not sure it's not a problem with Nuxt as I tried 4.31. and 4.2.2, and the problem still exists.
In any case, I think we should still leave this thread open so that it's easily discoverable by people running into the same issue.
